CREATE TABLE IF NOT EXISTS Pieces(id_piece INTEGER PRIMARY KEY, quantite INTEGER NOT NULL DEFAULT 0, disponible INTEGER NOT NULL DEFAULT 0, endommagee INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS Sets(id_exemplaire INTEGER PRIMARY KEY AUTOINCREMENT, id_set INTEGER NOT NULL, statut TEXT NOT NULL DEFAULT "détruit");
CREATE TABLE IF NOT EXISTS Minifigs(id_minifig INTEGER PRIMARY KEY, nb_exemplaires INTEGER NOT NULL DEFAULT 0);

CREATE TABLE IF NOT EXISTS Rangements_physiques(id_rangement INTEGER PRIMARY KEY AUTOINCREMENT, nom_rangement TEXT NOT NULL, type_rangement TEXT NOT NULL, nb_compartiments INTEGER NOT NULL DEFAULT 1, compartimentation TEXT NOT NULL DEFAULT "1 x 1", rangement_parent INTEGER);
CREATE TABLE IF NOT EXISTS Rangements_virtuels(id_rangement INTEGER PRIMARY KEY AUTOINCREMENT, rangement_physique INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS rangement_content(id_rangement INTEGER NOT NULL, id_element INTEGER NOT NULL UNIQUE, PRIMARY KEY (id_rangement, id_element));